INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('does this work','this is our first one', 'first writer', '1987-08-21');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('about tags','Tagtagtagtagtag', 'Tag writer', '1887-08-21');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('About history','History story, history history history', 'history writer', '2001-08-21');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('the story of dragons','DRAGONS BE HERE', 'Someone wrote this', '2009-08-21');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('5 Awesome PC Accessories You Should Buy','It’s finally done', 'IAN PAUL', '2021-05-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Do ISPs Track and Sell Your Browsing Data?','Is that even true, though? ', 'FERGUS O''SULLIVAN', '2021-05-04');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Everyone OVER 55 Needs Those Revolutionary Adjustable Focus Reading Glasses!','After the milestone age of 50, even the most perfect vision will start going downhill.', 'GEORGE LANE', '2021-04-21');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('How to Use and Edit Autofill for Forms in Firefox', 'Whether you choose to save addresses, payment methods, or both, you can speed up form entry using your web browser’s autofill settings.','SANDY WRITTENHOUSE', '2021-05-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Samson Q9U Broadcast Mic Review','Researching and investing in audio products is one of the greatest hurdles for amateur podcasters and streamers. ', 'ANDREW HEINZMAN ', '2021-05-04');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Galactic Starcruiser in 2022',' Disney just dropped the jaws of every Star Wars fan with a new “real” lightsaber.', 'SUZANNE HUMPHRIES', '2021-05-04');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Samsung Just Ended Support for Your Galaxy S8 Device','Four years after their release, Samsung is ending software support for the Galaxy S8 and S8+ smartphones.', 'ANDREW HEINZMAN', '2021-05-04');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Dell Patched a Critical Driver Flaw from 2009 Affecting Hundreds of PC Models','If you or anyone you know has a Dell computer, old or new, they should probably update it right away. ', 'IAN PAUL', '2021-05-04');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('The 10 Best Monitor Riser Stands','If you have a desktop computer, you need a monitor riser stand.', 'SARAH CHANEY ', '2021-05-03');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Microsoft is Killing the Adobe Flash Plugin on Windows 10','It’s finally done', 'SUZANNE HUMPHRIES ', '2021-05-03');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('From the Top','The software industry is always changing.', 'Cassandra Balentine', '2021-05-01');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Chasing the Giants','The modern supply chain is much different than ten or even five years ago.', ' Cassandra Balentine', '2019-11-18');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('env0 Extends Infrastructure ','env0, a provider of automated, collaborative remote-run workflow management for cloud deployments, today announced its advanced Infrastructure as Code Automation Platform with all-new Custom Flows feature.', 'Unknown', '2021-04-28');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Magic Software Introduces FactoryEye','FactoryEye leverages Magic Software’s four decades of industry knowledge, integration technologies and deployment of mission-critical systems to thousands of companies around the globe. ', 'Software Magazine', '2021-04-19');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('SmartBear Expands Support of Codeless, Automated Testing for Mobile and ERP Applications','SmartBear, a leading provider of software development and quality tools, has integrated TestComplete, its UI test automation tool, with BitBar, its native mobile device cloud. ', 'Software magazine', '2021-04-14');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('NASDAQ: PEGA','As digital expectations continue to skyrocket, organizations are turning to process automation to more efficiently assist their employees and customers. ', 'Pega', '2021-04-14');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Catchpoint Releases Enhanced Version of the WebPageTest API','We’re thrilled to make the WebPageTest API available to the entire development community', 'Patrick Meenan', '2021-04-06');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Applitools Announces Future of Testing','Applitools, provider of a next generation test automation through Visual AI and Ultrafast Test Cloud, today announced “Future of Testing: Mobile,” a free, live-streamed virtual event dedicated to the current trends and innovations shaping mobile test automation.', 'Paulina Grigonis', '2021-04-01');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Code Complete 2 ',' the Joy of Cooking for software developers. ', 'Steve McConnell', '2020-05-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('The Mythical Man-Month','Arguably the only classic book in our field. If you haven''t read it, shame on you.', 'Frederick Brooks', '2019-05-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Don`t make me think','The title says "web usability" but don''t be fooled by its faux specificity.', 'Steve Krug', '2021-02-28');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Rapid Development','Rapid Development isn''t about rapid development.', 'Steve McConnell', '2020-07-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Peopleware','If you''ve ever seen the performance of an all-star sports team suffer due to poor coaching, you''ll appreciate this book.', 'Tom DeMarco', '2018-07-07');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('The Design of Everyday Things','It can be incredibly frustrating to develop software, because so much can go wrong', 'Don Norman', '2017-05-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('About Face: The Essentials of Interaction Design','About Face is full of generally applicable guidelines for mobile and web.', 'Alan Cooper', '2017-10-06');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('The Inmates Are Running the Asylum',' Would our users want a print preview feature? ', 'Alan Cooper', '2017-08-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Programming Pearls',' It is the collective wisdom of many journeyman coders distilled into succinct, digestible columns.', 'Jon Bentley', '2018-12-06');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('The Pragmatic Programmer: From Journeyman to Master','why am I doing this?', 'Andrew Hunt', '2020-01-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Designing Web Usability','Designing Web Usability is of course a full-on web usability primer, so it''s a bit different than the GUI-oriented Cooper books.', 'Jacob Nielsen', '2019-04-04');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('The Visual Display of Quantitative Information','Information is beautiful. And so is a well-designed GUI.', 'Chris Sells', '2004-06-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Regular Expressions Cookbook','UNIX has a well-deserved reputation for being complex and impenetrable. So do Regular Expressions.', 'Jan Goyvaerts', '2017-03-15');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('HASH: a free, online platform for modeling the world','It’s finally done', 'Joel Spolsky', '2020-06-18');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Welcome, Prashanth!','Last March, I shared that we were starting to look for a new CEO for Stack Overflow. ', 'JOEL SPOLSKY', '2019-09-24');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('So, how’s that retirement thing going, anyway?','I’m chairman of three companies. You probably know all about Stack Overflow so I’ll skip ahead.', 'JOEL SPOLSKY', '2019-12-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Painless Bug Tracking','Keeping a database of bugs is one of the hallmarks of a good software team. ', 'JOEL SPOLSKY', '2000-11-08');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Daily Builds Are Your Friend','n 1982, my family took delivery of the very first IBM-PC in Israel.', 'JOEL SPOLSKY', '2001-01-27');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Don’t Let Architecture Astronauts Scare You','When great thinkers think about problems, they start to see patterns. ', 'JOEL SPOLSKY', '2001-04-21');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Hard-assed Bug Fixin’','Software quality, or the lack thereof, is something everybody loves to gripe about. ', 'JOEL SPOLSKY', '2001-07-31');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('A Hard Drill Makes an Easy Battle','I can’t say enough nice things about VMWare.', 'JOEL SPOLSKY', '2001-11-20');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Back to Basics','We spend a lot of time on this site talking about exciting Big Picture Stuff like .NET versus Java, XML strategy, Lock-In, competitive strategy, software design, architecture, and so forth. All this stuff is a layer cake, in a way.', 'JOEL SPOLSKY', '2011-12-11');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Five Worlds','Something important is almost never mentioned in all the literature about programming and software development, and as a result we sometimes misunderstand each other.', 'JOEL SPOLSKY', '2002-05-06');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('The Law of Leaky Abstractions','There’s a key piece of magic in the engineering of the Internet which you rely on every single day. ', 'JOEL SPOLSKY', '2002-11-11');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Craftsmanship','Making software is not a manufacturing process.', 'JOEL SPOLSKY', '2003-12-01');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Biculturalism','By now, Windows and Unix are functionally more similar than different. ', 'LIAN PAU', '2003-05-05');
INSERT INTO POST(TITLE, BODY, AUTHOR, PUBLISHED) VALUES ('Making Wrong Code Look Wrong','Way back in September 1983, I started my first real job, working at Oranim, a big bread factory in Israel that made something like 100,000 loaves of bread every night in six giant ovens the size of aircraft carriers.', 'ROCK STAR DEVELOPER', '2005-05-11');




INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('First!','Someone','1981-01-01',1);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Phht, what an original comment','SOmeJerk','1981-01-01',1);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('First!','SomeJerk','1981-01-01',2);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Cmon, leave them alone','WhiteKnighter78','1981-01-01',1);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Always wanted to learn more about it','Geek','2021-05-05',47);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Thanks for bring it up!','Startup founder','2021-05-04',6);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Five out of five!','Bach','2021-05-01',7);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Good job!','Marie Curie','2021-05-01',8);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Wow!','Someone','2021-01-01',23);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Back to coding!','Someone','2021-4-13',23);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Why not','Jeff Atwood','2021-3-9',6);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('This is great!','Mosh H','2021-01-01',24);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Learned something new','Marie Curie','2021-05-05',25);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Good to know','Emilie du Chatelet','2020-05-05',26);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Great intro!','Vera Rubin','2021-05-05',27);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Used it for my final project','Maria Merian','2021-05-05',28);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Can I use Python?','Sally Ride','2021-05-01',29);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('It is very detailed','Irene Curie','2021-05-05',30);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Great to know!','Rita Levi-Montalcini','2021-05-05',31);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Nope','Mae Jemison','2021-05-05',23);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('It teached you the essentials of coding','Grace Hopper','2021-05-05',32);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('I want to read more about it','Alice Ball','2021-05-05',32);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Could you recommend good resource?','Gertrude Elion','2021-05-05',33);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('All the concepts I need to know!','Emmy Noether','2021-05-05',31);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('WoW','Dorothy Hodgkin','2021-05-05',34);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Damn right','Katherine Johnsion','2021-05-05',35);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Great','Chien-Shiung Wu','2021-05-05',36);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('good job!','Mary Anning','2021-05-05',37);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('What to start with?','SAda Lovelace','2021-05-05',38);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('This is so convenient','Rachel Carson','2021-05-05',38);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('IntelliJ is amazing!','Barbara McClintock','2021-05-05',39);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('What to begin with','JOelyn Burnell','2021-05-05',39);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Depends on preferences','Lise Meitner','2021-05-05',40);
INSERT INTO COMMENT(BODY, AUTHOR, WRITTEN_ON, POST_ID ) VALUES('Good job!','Rosalind Franklin','1981-01-01',25);






INSERT INTO TAG(LABEL, POST_ID) VALUES('Tota  lly', 1);
INSERT INTO TAG(LABEL, POST_ID) VALUES('Tota  lly', 2);
INSERT INTO TAG(LABEL, POST_ID) VALUES('Tota  lly', 3);
INSERT INTO TAG(LABEL, POST_ID) VALUES('Tota  lly', 4);
INSERT INTO TAG(LABEL, POST_ID) VALUES('TestofThree', 1);
INSERT INTO TAG(LABEL, POST_ID) VALUES('TestofThree', 2);
INSERT INTO TAG(LABEL, POST_ID) VALUES('TestofThree', 3);
INSERT INTO TAG(LABEL, POST_ID) VALUES('prometheus', 1);
INSERT INTO TAG(LABEL, POST_ID) VALUES('SuperDuo', 1);
INSERT INTO TAG(LABEL, POST_ID) VALUES('SuperDuo', 2);
INSERT INTO TAG(LABEL, POST_ID) VALUES('Testof3', 1);
INSERT INTO TAG(LABEL, POST_ID) VALUES('Testof3', 2);
INSERT INTO TAG(LABEL, POST_ID) VALUES('Testof3', 3);
INSERT INTO TAG(LABEL, POST_ID) VALUES('1manband', 4);
INSERT INTO TAG(LABEL, POST_ID) VALUES('SOFTWARE', 44);
INSERT INTO TAG(LABEL, POST_ID) VALUES('CODE', 23);
INSERT INTO TAG(LABEL, POST_ID) VALUES('DEVELOPER', 6);
INSERT INTO TAG(LABEL, POST_ID) VALUES('DEVELOPER', 9);
INSERT INTO TAG(LABEL, POST_ID) VALUES('MESSY', 15);
INSERT INTO TAG(LABEL, POST_ID) VALUES('LEARN', 16);
INSERT INTO TAG(LABEL, POST_ID) VALUES('STYLE', 17);
INSERT INTO TAG(LABEL, POST_ID) VALUES('PROGRAMMER', 18);
INSERT INTO TAG(LABEL, POST_ID) VALUES('DEVELOPER', 19);
INSERT INTO TAG(LABEL, POST_ID) VALUES('MINDBLOWING', 34);
INSERT INTO TAG(LABEL, POST_ID) VALUES('CODE', 44);
INSERT INTO TAG(LABEL, POST_ID) VALUES('CODE', 23);
INSERT INTO TAG(LABEL, POST_ID) VALUES('LEARN', 20);
INSERT INTO TAG(LABEL, POST_ID) VALUES('LEARN', 21);
INSERT INTO TAG(LABEL, POST_ID) VALUES('MINDBLOWING', 22);
INSERT INTO TAG(LABEL, POST_ID) VALUES('MINDBLOWING', 25);
INSERT INTO TAG(LABEL, POST_ID) VALUES('MINDBLOWING', 26);
INSERT INTO TAG(LABEL, POST_ID) VALUES('MINDBLOWING', 27);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUILD', 28);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUILD', 29);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUILD', 30);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUILD', 31);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUILD', 33);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUILD', 18);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUILD', 19);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUG', 47);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUG', 45);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUG', 31);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUG', 32);
INSERT INTO TAG(LABEL, POST_ID) VALUES('BUG', 33);